events/urls.py
from django.urls import path
from .views import all_events_page, event_page


app_name = 'events'


urlpatterns = [
    path('', all_events_page, name="all_events_page"),
    path('<int:id>/', event_page, name="event_page"),
]

pages/urls.py
from django.urls import path
from .views import home_page, about_me, contact_page, gallery_page

urlpatterns = [
    path('', home_page, name='home_page'),
    path('about-me/', about_me, name="about_me"),
    path('contact/', contact_page, name="contact_page"),
    path('gallery/', gallery_page, name="gallery_page"),
]

posts/urls.py
from django.urls import path
from .views import all_posts_page, post_page


app_name = 'posts'


urlpatterns = [
    path('', all_posts_page, name="all_posts_page"),
    path('<int:id>/', post_page, name="post_page"),
]

pricing/urls.py
from django.urls import path
from .views import pricing_page


app_name = 'pricing'


urlpatterns = [
    path('', pricing_page, name="pricing_page"),
]

renatakrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('posts/', include('posts.urls')),
    path('events/', include('events.urls')),
    path('pricing/', include('pricing.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=250, blank=False, null=False)
    description = models.TextField(default="", blank=False, null=False)
    time = models.DateTimeField(blank=False, null=False)
    place = models.TextField(default="", blank=False, null=False)
    polish_date = models.CharField(max_length=128, blank=True, null=True, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        day = self.time.day
        month = self.time.month.numerator
        year = self.time.year
        time = self.time.time().isoformat().split(':')
        hour = time[0]
        minute = time[1]

        if month == 1:
            month = 'Styczeń'
        elif month == 2:
            month = 'Luty'
        elif month == 3:
            month = 'Marzec'
        elif month == 4:
            month = 'Kwiecień'
        elif month == 5:
            month = 'Maj'
        elif month == 6:
            month = 'Czerwiec'
        elif month == 7:
            month = 'Lipiec'
        elif month == 8:
            month = 'Sierpień'
        elif month == 9:
            month = 'Wrzesień'
        elif month == 10:
            month = 'Październik'
        elif month == 11:
            month = 'Listopad'
        elif month == 12:
            month = 'Grudzień'

        self.polish_date = str(f"{day} {month} {year} - {hour}:{minute}")

        return super(Event, self).save(*args, **kwargs)

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    choices = {
        ('YOGA', 'YOGA'),
        ('PILATES', 'PILATES'),
        ('GŁOS', 'GŁOS'),
        ('ŻYCIE', 'ŻYCIE'),
    }

    title = models.CharField(max_length=128, blank=False, null=False)
    description = models.TextField(default='', blank=False, null=False)
    kind = models.CharField(max_length=32, choices=choices, blank=False, null=False)
    cover = models.ImageField(upload_to='post_covers', blank=False, null=False)
    text = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(editable=False, default=timezone.now)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()

        return super(Post, self).save(*args, **kwargs)


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, blank=True, null=True)
    photo = models.ImageField(upload_to='photos', blank=False, null=False)

pricing/models.py
from django.db import models


class Price(models.Model):
    price = models.TextField(default="", blank=False, null=False)

    def __str__(self):
        return self.price

events/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Event


def all_events_page(request):
    all_events = Event.objects.all()
    events = []
    old_events = []
    today = timezone.now()

    for e in all_events:
        if today.isoformat() <= e.time.isoformat():
            events.append(e)
        else:
            old_events.append(e)

    old_events.reverse()
    events.reverse()

    context = {
        'old_events': old_events,
        'events': events
    }

    return render(request, 'events.html', context=context)


def event_page(request, id):
    event = Event.objects.get(pk=id)
    return render(request, 'event.html', {'event': event})

pages/views.py
from django.shortcuts import render
from posts.models import Post, Photo
from events.models import Event


def make_list(queryset):
    my_list = []

    for q in queryset:
        my_list.append(q)

    return my_list


def home_page(request):
    posts = Post.objects.all()
    posts_list = make_list(posts)
    new_posts = [posts_list.pop(), posts_list.pop(), posts_list.pop()]
    all_events = Event.objects.all()
    events_list = make_list(all_events)
    new_events = [events_list.pop(), events_list.pop(), events_list.pop()]
    all_photos = Photo.objects.all()
    photos = []

    for p in posts:
        photos.append(p.cover.url)

    for p in all_photos:
        photos.append(p.photo.url)

    context = {
        'posts': new_posts,
        'events': new_events,
        'photos': photos
    }

    return render(request, 'index.html', context=context)


def about_me(request):
    return render(request, 'about.html')


def contact_page(request):
    posts = Post.objects.all()
    all_photos = Photo.objects.all()
    photos = []

    for post in posts:
        photos.append(post.cover.url)

    for photo in all_photos:
        photos.append(photo.photo.url)

    return render(request, 'contact.html', {'photos': photos})


def gallery_page(request):
    posts = Post.objects.all()
    all_photos = Photo.objects.all()
    list_photos = []

    for post in posts:
        list_photos.append(post.cover.url)

    for photo in all_photos:
        list_photos.append(photo.photo.url)

    first_photo = list_photos[0]
    next_photos = [list_photos[1], list_photos[2], list_photos[3]]
    photos = []

    if len(list_photos) > 4:
        i = 4
        while i < len(list_photos) - 1:
            photos.append(list_photos[i])
            i += 1

    context = {
        'first_photo': first_photo,
        'next_photos': next_photos,
        'photos': photos
    }

    return render(request, 'gallery.html', context=context)

posts/views.py
from django.shortcuts import render
from .models import Post, Photo


def all_posts_page(request):
    posts = reversed(Post.objects.all())
    return render(request, 'posts.html', {'posts': posts})


def post_page(request, id):
    post = Post.objects.get(pk=id)
    all_photos = Photo.objects.filter(post=post.id)
    first_photos = []
    photos = []

    i = 0
    for photo in all_photos:
        if i < 3:
            first_photos.append(photo)
        else:
            photos.append(photo)

        i += 1

    context = {
        'post': post,
        'first_photos': first_photos,
        'photos': photos
    }

    return render(request, 'post.html', context=context)

pricing/views.py
from django.shortcuts import render
from .models import Price


def pricing_page(request):
    prices = Price.objects.all()
    return render(request, 'pricing.html', {'prices': prices})

events/templates/event.html
{% extends 'base_index.html' %}
{% load static %}

{% block styles %}
    <style>
        .log {
            color: black !important;
        }

        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <main class="main-content">
        <section class="section">
            <div class="container text-center align-content-center mt-8">
                <h2>{{ event.title }}</h2>
                <b>{{ event.polish_date }}</b>
                <hr>
                <b class="mt-7">Gdzie? - {{ event.place }}</b>
                <p class="mt-5">{{ event.description }}</p>
            </div>
        </section>
    </main>
{% endblock %}

events/templates/events.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - Wydarzenia</title>
{% endblock %}

{% block styles %}
    <style>
        .log {
            color: black !important;
        }

        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <main class="main-content">
        <section class="section">
            <div class="container">
                <h2 class="text-center mt-5">Nadchodzące wydarzenia</h2>
                <hr>
                <div class="row">
                    {% for e in events %}
                        <div class="col-md-4 mt-4">
                            <div class="card text-white bg-primary">
                                <div class="card-body">
                                    <h5 class="card-title">{{ e.polish_date }}</h5>
                                    <p>{{ e.title }}</p>
                                    <a class="fs-12 fw-600" href="{% url 'events:event_page' e.id %}">Zobacz <i class="fa fa-angle-right pl-1"></i></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <h3 class="text-center mt-8">Minione wydarzenia</h3>
                <hr>
                <div class="row">
                {% for e in old_events %}
                    <div class="col-md-4 mt-4">
                        <div class="card border hover-shadow-4">
                            <div class="card-body">
                                <h5 class="card-title">{{ e.polish_date }}</h5>
                                <p>{{ e.title }}</p>
                                <a class="fs-12 fw-600" href="{% url 'events:event_page' e.id %}">Zobacz <i class="fa fa-angle-right pl-1"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

pages/templates/about.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - O mnie</title>
{% endblock %}

{% block styles %}
    <style>
        .log {
            color: black !important;
        }

        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-center mt-10">
            <h1>Renata Król - O mnie</h1>
            <p>Yoga Głos Pilates</p>
        </div>
        <div class="text-center my-8">
            <img src="{% static 'img/renata.jpg' %}" alt="...">
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto mb-8">
                <p class="lead text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque ante non quam condimentum ultrices. Mauris consectetur quis lectus vitae sagittis. Aliquam imperdiet mattis lacinia. Sed interdum felis viverra ornare commodo. Mauris id libero velit. Aliquam eget finibus turpis. Cras sed felis arcu. Quisque eget finibus nibh. Proin lacus lorem, elementum nec sem et, imperdiet tempus lacus. Vivamus convallis sagittis porttitor. Mauris ac auctor massa, vel sollicitudin dolor.

Proin non consectetur mauris, non auctor metus. Phasellus vel turpis facilisis, aliquet arcu id, commodo lacus. Sed tincidunt nibh quis quam imperdiet dictum. Sed sit amet metus nisl. Sed vehicula nibh a ligula rutrum, et dapibus ante rhoncus. Phasellus eu consequat enim, nec pulvinar mi. In nec lobortis justo, et rhoncus tortor. Proin mollis bibendum scelerisque. Praesent iaculis dolor ut porttitor ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lobortis vehicula nisl vitae commodo. Cras vitae blandit dui.

Donec in lacinia velit. Aenean ut est elementum, fringilla orci fermentum, accumsan felis. Vestibulum et mattis mauris, nec pharetra diam. Suspendisse ac turpis a tellus accumsan finibus. Donec ornare rhoncus dolor, et hendrerit dolor dictum et. Phasellus id fringilla dolor. Cras rhoncus mi vitae lacinia rhoncus.

Morbi magna lectus, volutpat ac egestas a, lobortis at erat. Vivamus et velit sit amet leo accumsan efficitur. Aliquam blandit sit amet dui a posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur id lacus vel nunc tincidunt malesuada sit amet eget lacus. Phasellus vitae sapien aliquam, aliquet urna non, euismod nulla. Suspendisse vitae libero aliquet, blandit nulla non, auctor nulla. Cras elementum ipsum ligula, vitae facilisis diam elementum a. Donec suscipit dui eget odio vestibulum commodo.

Morbi posuere sapien turpis, ut maximus tellus lobortis a. Aenean imperdiet dictum risus, imperdiet consequat ex placerat ac. Quisque ornare est ut vestibulum consequat. Donec id efficitur urna. Sed mattis turpis sit amet orci fringilla egestas. In iaculis tellus dolor, ut volutpat purus pharetra eu. Aliquam vel cursus erat, nec porta est. Cras ut massa fringilla, luctus dui iaculis, malesuada ligula. Mauris pretium mattis urna a finibus. Donec nulla lacus, tempor ac nibh id, consectetur gravida orci. Etiam suscipit sed orci vel consequat. Donec non nibh ultricies, hendrerit orci ut, facilisis nisi. In maximus tellus ac enim consequat, sit amet gravida ipsum rutrum.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/base_index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">

      {% block title %}
        <title>Renata Król - Yoga Pilates Głos</title>
      {% endblock %}

    <!-- Styles -->
    <link href="{% static 'assets/css/page.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <style>
        @media (min-width: 0px) and (max-width: 900px) {
            .xd {
                margin-left: 25% !important;
            }
        }
    </style>

    {% block styles %}
    {% endblock %}

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'assets/img/favicon.png' %}">

    <!--  Open Graph Tags -->
    <meta property="og:title" content="Renata Król">
    <meta property="og:description" content="Renata Król - Yoga Pilates Głos">
    <meta name="twitter:card" content="summary_large_image">
  </head>

  <body>

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <!-- Scripts -->
    <script src="{% static 'assets/js/page.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>

  </body>
</html>

pages/templates/contact.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - Kontakt</title>
{% endblock %}

{% block styles %}
    <style>
        .log {
            color: black !important;
        }

        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <h1 class="mt-10 mx-auto">Renata Król - Kontakt</h1>
    <hr>

    <section class="section py-0">
        <div data-provide="slider" data-autoplay="true" data-slides-to-show="2" data-css-ease="linear" data-speed="12000" data-autoplay-speed="0" data-pause-on-hover="false">
            {% for photo in photos %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ photo }});"></div>
                </div>
            {% endfor %}
        </div>
    </section>

    <main class="main-content">
        <section class="section">
            <div class="container">
                <h1 class="mx-auto mt-6 text-center">Kontakt</h1>
                <hr>
                <h3 class="mx-auto text-center">Dane kontaktowe:</h3>
                <div class="container mb-10 text-center mt-7">
                    <p class="mx-auto">Numer telefonu: 784 123 099</p>
                    <p class="mx-auto">Adres e-mail: renatajustynakrol@gmail.com</p>
                    <p class="mx-auto">Facebook: Renata Król</p>
                    <p class="mx-auto">Instagram: renatakrol</p>
                </div>

            </div>
        </section>
    </main>
{% endblock %}

pages/templates/footer.html
<!-- Footer -->
  <footer class="footer">
    <div class="container">
      <div class="row gap-y align-items-center">

        <div class="col-6 col-lg-3">
        </div>

        <div class="col-lg-6">
          <div class="nav nav-bold nav-uppercase nav-trim justify-content-lg-center xd">
            <a class="nav-link" href="#">Facebook</a>
            <a class="nav-link" href="#">Instagram</a>
          </div>
        </div>

      </div>
    </div>
  </footer>
  <!-- /.footer -->

pages/templates/gallery.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - Galeria</title>
{% endblock %}

{% block styles %}
    <style>
        .log {
            color: black !important;
        }

        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center mt-10">Galeria</h1>
        <hr>

                <div class="row mb-7">
            <div class="col-lg-8 mx-auto">
                <div class="gallery gallery-4-type4" data-provide="photoswipe">
                    <a class="gallery-item" href="{{ first_photo }}">
                      <img src="{{ first_photo }}" alt="...">
                    </a>
                    <div class="gallery-item-group">
                        {% for p in next_photos %}
                            <a class="gallery-item" href="{{ p }}">
                                <img src="{{ p }}" alt="...">
                            </a>
                        {% endfor %}
                    </div>
                    <div class="gallery-extra-items">
                        {% for p in photos %}
                            <a class="gallery-item" href="{{ p }}">
                                <img src="{{ p }}" alt="...">
                            </a>
                        {% endfor %}
                    </div>
              </div>
            </div>
        </div>

    </div>
{% endblock %}

pages/templates/index.html
{% extends 'base_index.html' %}
{% load static %}

{% block styles %}
    <style>
        .navbar-open .navbar .nav-navbar>.nav-link {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- Header -->
    <header class="header text-white pt-12 pb-10" style="background-image: url({% static 'img/mainheader.jpeg' %}); min-height: 100vh;">
      <div class="container">
        <h2 class="display-4 mt-8">Renata Król</h2>
        <br>
        <h2 class="display-4">Yoga Pilates Głos</h2>
      </div>
    </header><!-- /.header -->


    <!-- Main Content -->
    <main class="main-content">


      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Populate the page
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <section class="section">
        <div class="container">
            <div class="container">
              <div class="row gap-y align-items-center" style="min-height: 70vh;">

                <div class="col-md-6 text-center text-md-right">
                  <h3 class="fw-500">Renata Król</h3>
                  <br>
                  <p>Nazywam się Renata Król a to jest moja strona internetowa. Znajdziesz tutaj dużo informacji na temat yogi, pilatesu oraz głosu, którymi zajmuję się zawodowo. Oprócz tego znajdziesz również ciekawe wpisy z mojego życia. W sekcji wydarzenia możesz także zobaczyć nadchodzące organizowane przeze mnie wydarzenia</p>
                </div>

                <div class="col-md-6">
                  <img class="rounded-md ml-md-4" src="{% static 'img/renia.jpg' %}" alt="...">
                </div>

              </div>
            </div>
        </div>
      </section>
        <section class="section py-0 mb-9">
            <div data-provide="slider" data-autoplay="true" data-slides-to-show="2" data-css-ease="linear" data-speed="12000" data-autoplay-speed="0" data-pause-on-hover="false">
                {% for p in photos %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ p }})"></div>
                </div>
                {% endfor %}
            </div>
        </section>

    <section class="section bg-dark text-white mb-7">
        <div class="container">
          <div class="text-center mb-8">
            <h2>Wydarzenia</h2>
            <p>Weź udział w nadchodzących wydarzeniach!</p>
          </div>


          <div class="row gap-y">

              {% for event in events %}
                <div class="col-lg-4">
                        <div class="card card-inverse">
                        <div class="card-body">
                            <h6 class="card-title fw-500">{{ event.polish_date }}</h6>
                            <p class="small-1">{{ event.title }}</p>
                            <a class="text-primary small-3 fw-600" href="{% url 'events:event_page' event.id %}">Zobacz <i class="ti-angle-right fs-7 pl-2"></i></a>
                        </div>
                    </div>
                </div>
              {% endfor %}

          </div>

        </div>
      </section>

        <section class="section mb-7 text-justify">
            <div class="container" style="font-size: 1.1rem;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam eaque ipsa iure non perspiciatis?
                    Commodi error eum nihil nisi pariatur repudiandae similique soluta vero. Dolor earum ipsum saepe
                    sapiente veritatis.

                Beatae et maiores necessitatibus nulla odio perspiciatis quam quisquam quod ullam, voluptate! A
                    accusamus architecto autem, dignissimos est fugit ipsam iste laboriosam molestias nobis nostrum
                    numquam officia quia soluta ut!
                Cupiditate, dolor fugiat harum reiciendis ut vitae. Fugit nostrum officia similique soluta vero.
                    Accusamus, dolores nam! Ducimus est harum incidunt officia placeat praesentium quis repudiandae
                    totam vel, voluptatibus! Similique, vel!

                Consequatur cumque esse explicabo ipsam nisi recusandae tempore ut voluptatibus voluptatum? At
                    blanditiis doloremque eligendi incidunt labore officiis placeat, quasi? Accusamus corporis
                    dignissimos, eveniet in mollitia omnis perferendis quaerat voluptatem.

               Accusamus aliquid animi at atque beatae consequatur corporis cum cupiditate distinctio, eaque ex,
                    fugit impedit ipsam laboriosam maxime minima natus rem repellat similique velit! Ducimus ipsa libero
                    quis temporibus voluptatibus!

            </div>
        </section>

      <section class="section text-white bg-fixed text-center py-11" style="background-image: url({% static 'img/ren.jpeg' %})" data-overlay="3">
        <div class="container">
          <h2 class="display-1"><strong>Yoga Pilates Głos</strong></h2>
        </div>
      </section>

    <section class="section">
        <div class="container">
            <header class="section-header">
                <small>Wpisy</small>
                <h2>Aktualności</h2>
                <hr>`
            </header>
            {% if posts.count != 0 %}

                {% for post in posts %}
                    <div class="row gap-y align-items-center bcard">

                        <div class="col-md-5 mx-auto">
                            <img class="rounded" src="{{ post.cover.url }}" alt="...">
                        </div>


                        <div class="col-md-6 text-center text-md-left">
                            <small>{{ post.kind }} {{ post.created_at }}</small>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.description }}</p>
                            <br>
                            <a class="btn btn-outline-danger" href="{% url 'posts:post_page' post.id %}">Zobacz post <i class="ti-arrow-right fs-9 ml-2"></i></a>
                        </div>

                    </div>
                {% endfor %}

            {% endif %}

        </div>
    </section>

    </main>

{% endblock %}

pages/templates/navbar.html
 <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-stick-dark" data-navbar="sticky">
    <div class="container">

      <div class="navbar-left">
        <button class="navbar-toggler" type="button">&#9776;</button>
        <a class="navbar-brand" href="{% url 'home_page' %}">
          <h1 class="logo-light log">RenataKrol.pl</h1>
          <h1 class="logo-dark log" style="color: white;">RenataKrol.pl</h1>
        </a>
      </div>

      <section class="navbar-mobile">
        <span class="navbar-divider d-mobile-none"></span>

        <nav class="nav nav-navbar">
          <a class="nav-link nl" href="{% url 'home_page' %}" style="color: white;">Strona główna</a>
          <a class="nav-link nl" href="{% url 'posts:all_posts_page' %}" style="color: white;">Wpisy</a>
          <a class="nav-link nl" href="{% url 'events:all_events_page' %}" style="color: white;">Wydarzenia</a>
          <a class="nav-link nl" href="{% url 'about_me' %}" style="color: white;">O mnie</a>
          <a class="nav-link nl" href="{% url 'contact_page' %}" style="color: white;">Kontakt</a>
          <a class="nav-link nl" href="{% url 'gallery_page' %}" style="color: white;">Galeria</a>
            <a class="nav-link nl" href="{% url 'pricing:pricing_page' %}" style="color: white;">Cennik</a>
        </nav>
      </section>


    </div>
  </nav>

posts/templates/posts.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - Posty</title>
{% endblock %}

{% block styles %}
    <style>
        .nl {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <header class="header text-white pt-12 pb-10" style="background-image: url({% static 'img/rpk.jpg' %});">
        <div class="container">
            <h2 class="display-4">Renata Król</h2>
            <br>
            <h2 class="display-4">Yoga Pilates Głos</h2>
        </div>
    </header>

    <main class="main-content">
        <section class="section">
            <div class="container">
                <header class="section-header">
                <small>Posty</small>
                <h2>Aktualności</h2>
                <hr>
                </header>

                {% for post in posts %}
                    <div class="row gap-y align-items-center bcard mb-5">
                        <div class="col-md-5 mx-auto">
                            <img class="rounded" src="{{ post.cover.url }}" alt="...">
                        </div>

                        <div class="col-md-6 text-center text-md-left">
                            <small>{{ post.kind }} {{ post.created_at }}</small>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.description }}</p>
                            <br>
                            <a class="btn btn-outline-danger" href="{% url 'posts:post_page' post.id %}">Zobacz post <i class="ti-arrow-right fs-9 ml-2"></i></a>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </section>
    </main>

{% endblock %}

pricing/templates/pricing.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Renata Król - Cennik</title>
{% endblock %}

{% block styles %}
    <style>
        .navbar-open .navbar .nav-navbar>.nav-link {
            color: #757575 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <section class="section text-white" style="background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh;">
        <canvas class="constellation" width="1440" height="727"></canvas>

        <div class="container">
          <header class="section-header">
            <small>Yoga Pilates Głos</small>
            <h2>Cennik</h2>
            <hr>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ab, aperiam aspernatur beatae doloribus est ex exercitationem hic magnam magni mollitia necessitatibus quaerat? Dicta doloremque excepturi minima non pariatur quasi.</p>
          </header>

            {% for price in prices %}
                <p class="text-center">{{ price }}</p>
            {% endfor %}

        </div>
      </section>
{% endblock %}